# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c8b71925-2f08-4d76-8891-1431715ddfbe";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9d82af98-a19f-4c70-9d7e-4e6621c9156d";
      fsType = "ext4";
    };

  swapDevices = [
    { device = "/dev/disk/by-uuid/6a2ac3d4-a2e8-47c7-902c-7c507e12ebc2"; }
  ];

  nix.maxJobs = lib.mkDefault 2;
  #networking.enableIntel3945ABGFirmware = true;
  hardware.enableRedistributableFirmware = true;
}
